#!/bin/bash
Start="1"
end="254"
begin="10.0.5"

for 1 in $(eval echo "{$Start .. $end}")
do
ping -c 1 -w 1 "${begin}.${1}" | grep "64 bytes" | grep -E -o "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"
done
